

/** 
*  Constantes con valores de URL´s relacionadas con el componente 
*/
export const PATHS = {
    path_administracion_usuario_autocomplete: '/api/usuario/searchAutocomplete',
    path_administracion_usuario_autocomplete_nombres: '/api/usuario/searchAutocomplete/nombres',
    path_administracion_zonas: '/api/administracion/ubicaciones/zona',
    path_administracion_localidades: '/api/administracion/ubicaciones/localidad',
    path_administracion_barrios: '/api/administracion/ubicaciones/barrio',
    path_administracion_uplas: '/api/administracion/ubicaciones/upla',
    path_administracion_cuadrantes: '/api/administracion/ubicaciones/cuadrante',
    path_administracion_actividades: '/api/administracion/actividad',
    path_administracion_persona_autocomplete: '/api/administracion/persona/searchAutocomplete',
    path_administracion_persona_ingeniero_disenio_autocomplete: '/api/administracion/persona/autocompleteIngenieroDisenio',
    path_administracion_usuario_director_obra_autocomplete: '/api/usuario/searchDirObraAutocomplete',
};



/**
 * Hommologación de las constantes de permisos usados por el componente 
 * con los asignados en la base de datos
 */
export const PERMISOS = {

};

export const GRID_MANTENIMIENTOS_CONSTANTS = {
    tipoGrid: 'Invisible',
    itemPorPagina: 'Elementos por página',
    si: 'SI',
    no: 'NO',
    aledano: 'ALEDAÑO',
    posicion: 'No.',
    id: 'Id',
    pk: 'PK',
    civ: 'CIV',
    solicitudRadicadoEntrada: 'Radicado Entrada',
    solicitudFechaVinculacion: 'Fecha Vinculación',
    solicitudRadicadoSalida: 'Radicado Salida',
    origen: 'Origen',
    estadoPk: 'Estado de PK',
    fechaAsignacion: 'Fecha Asignación',
    fechaVencimiento: 'Fecha Vencimiento',
    kmCarrilImpacto: 'KM Carril del PK',
    ancho: 'Ancho',
    area: 'Area',
    longitud: 'Longitud',
    indicePriorizacion: 'Indice Priorización',
    responsable: 'Responsable',
    radicadoSolicitudReserva: 'Radicado Solicitud Reserva',
    radicadoRespuestaReserva: 'Radicado Respuesta de Reserva',
    tipoMalla: 'Tipo Malla',
    tipoUsoVia: 'Uso de la Via',
    fechaVisitaTecnica: 'Fecha Última Visita Técnica',
    fechaInstalacion: 'Fecha Instalación Solicitud',
    radicadoIntervencion: 'Radicado de Intervención',
    radicadoInterExclusivo: 'Radicado de Intervención',
    localidad: 'Localidad',
    zona: 'Zona',
    barrio: 'Barrio',
    estadoMantenimiento: 'Estado Actividad',
    cuadrante: 'Cuadrante',
    cantidadApiques: 'Cantidad Apiques',
    actividadSolicitudApique: 'Actividad Solicitud Apique',
    aforos: 'Aforos',
    prioritarios: 'Prioritarios',
    solicitud: 'Solicitud',
    tipoActividad: 'Tipo Actividad',
    upla: 'UPZ',
    actividadActual: 'Actividad Actual',
    actividad: 'Actividad',
    requiereApique: 'Requiere Apique',
    requiereAforo: 'Requiere Aforo',
    tipoIntervencion: 'Tipo Intervención',
    tipoIntervencionPriorizacion: 'Tipo Intervención',
    tipoSuperficie: 'Tipo Superficie',
    direccion: 'Direccion',
    fechaProgramacionVisita: 'Fecha Programación Visita',
    numeroMovilVisitaTecnica: 'Identificacion vehiculo Visita tecnica',
    ejeVial: 'Eje vial',
    desde: 'Eje Vial Desde',
    hasta: 'Eje Vial Hasta',
    numeroCarriles: 'Número de Carriles',
    responsableVisitaTecnica: 'Responsable Visita Técnica',
    responsableRevision: 'Responsable de Revisión',
    observacionDireccionApique: 'Observación',
    directorDeObra: 'Director de Obra',
    directorDeObraXZona: 'Director de Obra',
    intervencionAgrupada: 'Intervención Agrupada',
    intervencionDetallada: 'Intervención Detallada',
    fechaInicioVisita: 'Fecha de inicio visita',
    fechaFinVisita: 'Fecha final de visita',
    nomenclatura: 'Nomenclatura',
    estrategia: 'Estrategia',
    estrategiaIntervencion: 'Estrategia intervención',
    observacionActividadActual: 'Observación Actividad Actual',
    observacionApiqueUltimaSolicitudApique: 'Observación Apique Ultima Solicitud Apique',
    rutasTransporte: 'Transporte',
    levantamientoTopografico: 'Levantamiento Topografico',
    modulacionLosas: 'Modulación Losas',
    fichaEvaluacionEstructural: 'Ficha Evaluación Estructural',
    informacionDeDisenio: 'Información de Diseño',
    consultaRedes: 'Consulta Redes',
    posibleDanioRedes: 'Posible daño en Redes',
    tieneRadicadoSalida: 'Tiene Radicado de Salida',
    tipoRadicadoRespuestaReserva: 'Tipo Radicado Respuesta Reserva',
    fechaAsignacionIngenieroDisenio: 'Fecha Asignación Ingeniero de Diseño',
    ingenieroDisenio: 'Ingeniero de Diseño',
    listaIngenierosDisenio: 'Ingeniero de Diseño',
    nombreResidenteSocial: 'Nombre Residente Social',
    jornadaProgramacionPeriodica: 'Jornada Programacion',
    fechaSolicitudSmvl: 'Fecha Solicitud SMVL',
    numeroRadicadoSmvl: 'Número Radicado SMVL',
    observacionesSmvl: 'Observación SMVL',
    listaChequeoSmvl: 'Lista Chequeo SMVL',
    listaChequeoGasa: 'Lista Chequeo GASA',
    fechaSolicitudGasa: 'Fecha Solicitud GASA',
    numeroRadicadoGasa: 'Número Radicado GASA',
    observacionesGasa: 'Observcaiones GASA',
    estadoProgramacionVisita: 'Estado Programación Visita',
    estadoProgramacionDiaria: 'Estado Programación Diaria',
    fechaProgramacionDiaria: 'Fecha Programación Diaria',
    jornada: 'Jornada',
    jornadaProgDiaria: 'Jornada',
    fechaInforme: 'Fecha Informe',
    estadoObra: 'Estado Obra',
    estadoRegistroDiarioCuadrilla: 'Estado Registro Diario Cuadrilla',
    avancePorcentajeAcumuladoObra: 'Avance Porcentaje Acumulado Obra',
    kmCarrilLineal: 'Km Carril Lineal',
    kmCarrilObra: 'Km Carril Obra',
    vigencia: 'Vigencia',
    periodicidad: 'Periodicidad',
    periodo: 'Período',
    duracionPlaneada: 'Duración Planeada',
    estadoProgramacionPk: 'Estado Programación Pk',
    estadoProgramacion: 'Estado Programación',
    programa: 'Programa',
    estadoActividad: 'Estado Actividad',
    turnoResidenteSocial: 'Turno Ejecución Residente Social',
    tipoSeccionVial: 'Sección Vial',
    enSeguimiento: 'En Seguimiento',
    fechaSeguimiento: 'Fecha Segimiento',
    residenteSocial: 'Residente Social',
    tieneResidenteSocial: 'Residente Social Asignado',
    turnoResidenteAmbiental: 'Turno Ejecución Residente Ambiental',
    nombreResidenteAmbiental: 'Nombre Residente Ambiental',
    residenteAmbiental: 'Residente Ambiental',
    tieneResidenteAmbiental: 'Residente Ambiental Asignado',
    turnoResidenteSST: 'Turno Ejecución Residente SST',
    nombreResidenteSST: 'Nombre Residente SST',
    residenteSST: 'Residente SST',
    tieneResidenteSST: 'Residente SST Asignado',
    fechasIntervencion: 'fechas Intervencion',
    origenSin: 'origen',
    requiereActualizacionDiagnostico: 'Requiere Act. Diagnóstico',
    numeroActaIntervencion: 'Número Acta Intervención',
    tieneSolicitudLaboratorio: 'Tiene Solicitud Laboratorio',
    espesorDisenio: 'Espesor Diseño',
    tipoResultado: 'Tipo Resultado',
    formatoDDMMYYYY: 'DD-MM-YYYY',
    frecuencia: 'Frecuencia',
    tipoMezcla: 'Tipo Mezcla',
    fechaDespacho: 'Fecha Despacho',
    fechaSolicitud: 'Fecha Solicitud',
    tipoMaterial: 'Tipo Material',
    responsableObra: 'Responsable de obra',
    telResponsableObra: 'Tel responsable de obra',
    fechaProgramacionIntervencion: 'Fecha programación intervencion',
    turnoEjecucionIntervencion: 'Turno de ejecución',
    estadoInspeccionIntervencion: 'Estado inspección intervención',
    cantidadArbolesIntervencion: 'Cantidad árboles',
    cantidadProtArbolesIntervencion: 'Cantidad árboles protegidos',
    cantidadSumiderosIntervencion: 'Cantidad sumideros',
    cantidadProtSumiderosIntervencion: 'Cantidad sumideros protegidos',
    cantidadEspacioPublicoIntervencion: 'Cantidad espacio público',
    cantidadEscombrosIntervencion: 'Cantidad escombros',
    destinoEscombrosIntervencion: 'Escombros destino',
    cantidadBanosInervencion: 'Baños',
    cantidadBanosMantenIntervencion: 'Baños con mantenimiento',
    otrosDocumentos: 'Otros documentos',
    actividadAgrupada: 'Actividad agrupada',
    descripcionActividadAgrupada: 'Actividad agrupada',
    fechaVisitaDisenio: 'Fecha Visita Diseño',
    fechaSolicitudEnsayo: 'Fecha solicitud',
    tipoEnsayo: 'Tipo Ensayo',
    fechaRegistroEnsayo: 'Fecha ensayo',
    excel: 'excel',
    pdf: 'pdf',
    ...PATHS,
    ...PERMISOS
};
