/**
 * Declaración de constantes de etiquetas propias usadas en el componente
 */
export const CONST_SHARED = {
  acciones: 'Acciones',
  actualizacionExitosa: '¡Se actualizaron los datos con exito!',
  actualizacionExitosaReasignacion: '¡Se actualizaron los datos con exito! No olvide asignar el usuario a la gestión asignada',
  actualizar: 'Actualizar',
  actualMente: 'Actualmente tiene ',
  adjuntarFile: 'Adjuntar archivo',
  agregar: 'Agregar',
  anterior: 'Anterior',
  archivo: 'Archivo',
  asignar: 'Asignar',
  al: 'Al',
  atras: 'Ir Atrás',
  irAtras: 'Ir Atrás',
  badRequest: 'Solicitud incorrecta',
  buscar: 'Buscar',
  campoMaximo: 'El valor no puede ser mayor al valor máximo',
  campoNoVacio: 'El campo no puede estar vacio.',
  campoNoVinculado: 'El radicado no ha sido vinculado',
  campoNumerico: 'El campo debe ser numérico',
  campoNoFormato: 'El campo no cumple con el formato',
  campoRequerido: 'El campo es requerido.',
  cancelar: 'Cancelar',
  todos: 'Todos',
  capasDesactivadas: 'Capas Desactivadas',
  caracteres: 'caracteres',
  cerrar: 'Cerrar',
  confirmar: {
    mensaje: '¿Desea confirmar la acción actual?',
    titulo: 'Confirmando acción'
  },
  consultar: 'Consultar',
  crear: 'Crear',
  crearNuevo: 'Crear nuevo',
  datosNecesarioLugar: 'El lugar no posee la configuración necesario para la disponibilidad',
  datepicker: {
    placeholder: 'Calendario',
    types: {
      calendar: 'calendar',
      timer: 'timer',
      dateTime: 'datetime',
      fullCalendar: 'both'
    }
  },
  deleteError: 'Se presento un problema con el servidor, por favor comuníquese con el administrador',
  deleteSuccess: '¡Se elimino el elemento!',
  descargar: 'Descargar',
  deseaSalir: '¿Desea salir de la acción actual?',
  detalle: 'Detalle',
  direccion: 'Dirección',
  editar: 'Editar',
  aniadir: 'Añadir',
  adjuntar: 'Adjuntar',
  ejecutar_transicion: 'Ejecutar Transició',
  elemento: 'elemento',
  eliminar: 'Eliminar',
  eliminarPregunta: '¿Desea eliminar el registro?',
  eliminarRegistro: '¿Desea eliminar el registro?',
  eliminarTodoMensaje: 'Elimina todos los archivos ya existentes',
  enviar: 'Enviar',
  errorCargaFileMensaje: 'Se presento un problema con la carga del archivo, por favor intentelo de nuevo',
  error500: 'Se presento un problema con el servidor, por favor comuníquese con el administrador',
  errorDescargarArchivo: 'Error al descargar el formato',
  errorForm: 'Favor revise el formulario',
  errorMessage: 'No se encuentran resultados.',
  errorSubirArchivo: 'Se presento un problema al subir el archivo adjunto',
  estadosCapaPk: {
    sinGestion: 'NULL',
    prediagnostico: '0',
    terminado: '1',
    enEjecucion: '2',
    suspendido: '3',
    porEjecutar: '4',
    diagnosticado: '5',
    seguimiento: '6',
    priorizado: '7',
    terminadoExcluido: '8',
    viablePriorizacion: '9',
    historicoMigrado: '19',
    terminadoNoViable: '20',
    terminadoReservaRechaza: '21',
    terminadoBuenEstado: '22',
    terminadoVigenciaDiagnostico: '23',
    reservado: '24',
    terminadoBuenEstadoSeguimiento: '25',
    terminadoActualizacionDiagnostico: '26'
  },
  exportar: 'Exportar',
  exportarExcel: 'Exportar a excel',
  favorReviseFormulario: 'Favor revise el formulario',
  fecha: 'Fecha',
  fechaMinima: 'La fecha mínima no es valida',
  fechaMaxima: 'La fecha máxima no es valida',
  maxSizeFiled: 'El tamaño total no debe exceder ',
  fileSize: 'El tamaño del archivo no puede ser mayor de: ',
  formato_correo: 'El campo no tiene un formato de correo electrónico válido',
  formato_numero: 'El campo no tiene un valor válido',
  formatoFecha: 'La fecha ingresada para el calendario no es la esperada "DD-MM-YYYY" o "DD-MM-YYYY HH:mm:ss"',
  guardar: 'Guardar',
  guardarTodo: 'Guardar todo',
  guardarSeccion: 'Guardar sección',
  horaFinMenor: 'La hora fin no puede ser menor a la hora inicio',
  horaInicioMayor: 'La hora inicio no puede ser mayor a la hora fin',
  importar: 'Importar',
  informacionCampoObligatorio: 'Todos los campos con * son obligatorios',
  informacionGeneral: 'Información general',
  intervaloFechasNoPermitido: 'El intervalo descrito en el rango de fechas no es  permitido',
  intervaloNoPermitido: 'El intervalo de horas ingresado supera el rango permitido',
  itemPorPagina: 'Elementos por página',
  limpiar: 'Limpiar',
  loginIncorrecto: 'Usuario o clave incorrectos',
  longitud_maxima: 'El campo debe tener una longitud máxima de ',
  valor_maxima: 'El campo debe tener un valor máximo de ',
  longitud_mimina: 'El campo debe tener una longitud mínima de ',
  valor_mimina: 'El campo debe tener un valor mínimo de ',
  longitud_decimal_maxima: 'El dato no debe tener más de 2 decimales',
  minimo: 'El valor debe ser superior a ',
  mantenimiento: 'Mantenimiento',
  maximo: 'El campo admite máximo 28 unidades',
  maximoGeneral: 'El valor debe ser inferior a ',
  maximoOigual: 'El valor debe ser inferior o igual a ',
  valorSuperiorA: 'El valor máximo excedido',
  valormaximo: 'El valor no puede ser superior a ',
  maxElements: 'El total de elementos no debe exceder ',
  maxFiles: 'El total de elementos no debe exceder ',
  minElements: 'El total de elementos no debe ser menos de ',
  minFiles: 'El total de elementos no debe ser menos de ',
  mensajeErrorServidor: 'Se presento un problema con el servidor, por favor comuníquese con el administrador',
  no: 'No',
  noDocumento: 'No hay documento',
  noEncontrado: '',
  noRadicado: 'El radicado no fue encontrado',
  noResultados: 'No se encuentran resultados.',
  noResultadosEstado: 'No se encuentran resultados para este estado.',
  nombre: 'Nombre',
  apellido: 'Apellido',
  objeto: 'objeto',
  placeholder: 'Placeholder',
  procesar: 'Procesar',
  proceso: 'Proceso',
  procesoInfo: {
    noEjecutar: 'No se puede continuar con el proceso porque ya ha finalizado',
    noTransiciones: 'El proceso no cargo o no tienes transiciones',
    tieneRadicadoSalida: 'No se puede ejecutar el proceso, una o más solicitudes tiene un radicado de salida.',
    procesoActivo: 'No se puede ejecutar el proceso, una o más solicitudes ya tiene un proceso en estado de enviado a programación'
  },
  radicado: {
    numero: 'Nro Radicado ',
    fechaRadicado: 'Fecha Radicado Orfeo',
    fechaVencimiento: 'Fecha Vencimiento',
    entidad: 'Entidad',
    remitente: 'Remitente',
    asunto: 'Asunto'
  },
  registro: 'Registro',
  registros: 'Registros',
  seleccionar: 'Seleccionar',
  si: 'Si',
  siguiente: 'Siguiente',
  successDelete: '',
  successEdit: '¡Se actualizaron los datos con exito!',
  successSave: '¡Registro creado con exito!',
  trabajar: 'Trabajar',
  transicion: 'Transición',
  transicionInfo: {
    transicion: 'Seleccione Transición',
    documentos: 'Ingrese Documentos',
    responsable: 'Seleccione Responsable',
    observaciones: 'Ingrese Observaciones'
  },
  total: 'Total',
  type: 'Tipo',
  currentAction: {
    consolidadoBanosPortatiles: 'consolidadoBanosPortatiles',
    consultarCierreAmbiental: 'consultarCierreAmbiental',
    detalleDiagnosticar: 'detalleDiagnosticar',
    historicoDocumento: 'historicoDocumento',
    detalleVisitaIntervencion: 'detalleVisitaIntervencion',
    revisarDiseno: 'revisarDiseno',
    vistaConjunta: 'vistaConjunta',
    disenoApique: 'disenoApique',
    list: 'list',
    programarBanosPortatiles: 'programarBanosPortatiles',
    registrarCierreAmbiental: 'registrarCierreAmbiental',
    registrarProgramacionDiaria: 'registrarProgramacionDiaria',
    listarProgramacionDiaria: 'listarProgramacionDiaria',
    enviarProgramacionDiaria: 'enviarProgramacionDiaria',
  },
  typeFiles: 'El componente solo permite usar los formatos de archivo: ',
  unauthorized: 'Es necesario autenticar para obtener la respuesta solicitada',
  urlLoginNoValida: 'La url de validación no econtrada',
  validar: 'Validar',
  valorMinimo: 'El valor mínimo del campo no puede ser menor a cero (0).',
  valorMaximo: 'El valor máximo del campo no puede ser mayor a 9007199254740991.',
  valores_positivos: 'El campo no admite valores negativos',
  errorFechaDiaNoHabil: 'La visita no se puede programar para días sábados, domingos o festivos',
  velocidadPromedio: 24,
  vincular: {
    titulo: 'Vincular',
    mensaje: '¿Desea vincular el radicado de entrada?'
  },
  enviarSolicitud:'Enviar Solicitud',
  volver: 'Volver',
  IrAtras: 'Ir Atrás',
  ProgramarOtros: 'Programar Otros',
  week: {
    lunes: 'Lunes',
    martes: 'Martes',
    miercoles: 'Miércoles',
    jueves: 'Jueves',
    viernes: 'Viernes',
    sabado: 'Sábado',
    domingo: 'Domingo'
  },
  activo: 'Activo',
  descripcion: 'Descripción',
  item: 'Item',
  formatoArchivos: [
    { mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', nombreTipoArchivo: 'Excel 2007 en adelante'},
    { mimeType: 'application/vnd.ms-excel', nombreTipoArchivo: 'Excel 2003'},
    { mimeType: 'application/pdf', nombreTipoArchivo: 'Pdf'},
    { mimeType: 'application/zip', nombreTipoArchivo: 'Carpeta comprimida ZIP'},
    { mimeType: 'application/x-zip-compressed', nombreTipoArchivo: 'Carpeta comprimida ZIP'},
    { mimeType: 'image/*', nombreTipoArchivo: 'Todos los formatos de Imagenes'},
    { mimeType: 'image/jpeg', nombreTipoArchivo: 'Imágen formato jpeg-jpg'},
    { mimeType: 'image/gif', nombreTipoArchivo: 'Imágen formato gif'},
    { mimeType: 'image/bmp', nombreTipoArchivo: 'Imágen formato bmp'},
    { mimeType: 'image/png', nombreTipoArchivo: 'Imágen formato png'},
    { mimeType: 'image/svg+xml', nombreTipoArchivo: 'Imágen formato svg-svgz'},
    { mimeType: 'image/tiff', nombreTipoArchivo: 'Imágen formato tif-tiff'},
    { mimeType: 'image/vnd.wap.wbmp ', nombreTipoArchivo: 'Imágen formato wbmp'},
    { mimeType: 'image/webp', nombreTipoArchivo: 'Imágen formato webp'},
    { mimeType: 'image/x-jng', nombreTipoArchivo: 'Imágen formato jng'},
    { mimeType: 'image/x-icon', nombreTipoArchivo: 'Imágen (icono) formato cur-ico'}
  ]
};

export const UMV_DATES_FORMATS = {
  path_menu: '/api/administracion/menu',
  parse: {
    dateInput: 'DD/MM/YYYY'
  },
  display: {
    dateInput: 'DD/MM/YYYY',
    monthYearLabel: 'MM YYYY',
    dateA11yLabel: 'DD/MM/YYYY',
    monthYearA11yLabel: 'MM YYYY'
  }
};
