

/** 
*  Constantes con valores de URL´s relacionadas con el componente 
*/
export const PATHS = {
    path_administracion_usuario_autocomplete: '/api/usuario/searchAutocomplete',
    path_administracion_zonas: '/api/administracion/ubicaciones/zona',
    path_administracion_localidades: '/api/administracion/ubicaciones/localidad',
    path_administracion_barrios: '/api/administracion/ubicaciones/barrio',
    path_administracion_uplas: '/api/administracion/ubicaciones/upla',
    path_administracion_cuadrantes: '/api/administracion/ubicaciones/cuadrante',
    path_administracion_actividades: '/api/administracion/actividad',
    path_administracion_persona_autocomplete: '/api/administracion/persona/searchAutocomplete',
    path_administracion_persona_ingeniero_disenio_autocomplete: '/api/administracion/persona/autocompleteIngenieroDisenio',
};



/**
 * Hommologación de las constantes de permisos usados por el componente 
 * con los asignados en la base de datos
 */
export const PERMISOS = {

};

export const DETALLE_CIERRE_INTERVENCION_CONSTANTS = {
    estrategia: 'Estrategía',

    tipoGrid: 'Invisible',
    itemPorPagina: 'Elementos por página',
    si: 'SI',
    no: 'NO',
    posicion: 'No.',
    id: 'Id',
    pk: 'PK',
    civ: 'CIV',
    civEjecutado: 'N° CIV Ejecutado',
    solicitudRadicadoEntrada: 'Radicado Entrada',
    solicitudFechaVinculacion: 'Fecha Vinculación',
    solicitudRadicadoSalida: 'Radicado Salida',
    origen: 'Origen',
    estadoPk: 'Estado de PK',
    fechaAsignacion: 'Fecha Asignación',
    fechaVencimiento: 'Fecha Vencimiento',
    kmCarrilImpacto: 'KM Carril del PK',
    kmCarrilIntervencion: 'KM Carril Intervención',
    ancho: 'Ancho',
    anchoSegmentoVial: 'Ancho segmento vial',
    numHuecosLosas: 'N° de huecos / N° losas',
    area: 'Area',
    areaTotalIntervenida: 'Área total intervenida',
    longitud: 'Longitud',
    longitudTotalIntervenida: 'Longitud total intervenida',
    longitudSegmentoVial: 'Longitud segmento vial',
    indicePriorizacion: 'Indice Priorización',
    responsable: 'Responsable',
    cargo: 'Cargo',
    radicadoSolicitudReserva: 'Radicado Solicitud Reserva',
    radicadoRespuestaReserva: 'Radicado Respuesta de Reserva',
    tipoMalla: 'Tipo Malla',
    tipoUsoVia: 'Uso de la Via',
    fechaVisitaTecnica: 'Fecha Última Visita Técnica',
    radicadoIntervencion: 'Radicado de Intervención',
    localidad: 'Localidad',
    zona: 'Zona',
    barrio: 'Barrio',
    estadoMantenimiento: 'Estado Mantenimiento',
    cuadrante: 'Cuadrante',
    cantidadApiques: 'Cantidad Apiques',
    actividadSolicitudApique: 'Actividad Solicitud Apique',
    aforos: 'Aforos',
    prioritarios: 'Prioritarios',
    solicitud: 'Solicitud',
    tipoActividad: 'Tipo Actividad',
    tipoActividadAgrupada: 'Tipo Actividad',
    upla: 'UPZ',
    actividadActual: 'Actividad Actual',
    actividad: 'Actividad',
    requiereApique: 'Requiere Apique',
    requiereAforo: 'Requiere Aforo',
    tipoIntervencion: 'Tipo Intervención',
    tipoIntervencionPriorizacion: 'Tipo Intervención',
    direccion: 'Direccion',
    fechaProgramacionVisita: 'Fecha Programación Visita',
    numeroMovilVisitaTecnica: 'Identificacion vehiculo Visita tecnica',
    desde: 'Eje Vial Desde',
    hasta: 'Eje Vial Hasta',
    numeroCarriles: 'Número de Carriles',
    responsableVisitaTecnica: 'Responsable Visita Técnica',
    responsableRevision: 'Responsable de Revisión',
    observacionDireccionApique: 'Observación Dirección Apique',
    directorDeObra: 'Director de Obra',
    intervencionAgrupada: 'Intervención Agrupada',
    intervencionDetallada: 'Intervención Detallada',
    fechaInicioVisita: 'Fecha Inicial de Programación de Intervencion',
    fechaInicioIntervencion: 'Fecha Inicio Intervención',
    fechaInicioEjecucion: 'Fecha Inicio Ejecución',
    fechaFinEjecucion: 'Fecha Fin Ejecución',
    fechaFinVisita: 'Fecha Final de Programación de Intervencion',
    nomenclatura: 'Nomenclatura',
    observacionActividadActual: 'Observación Actividad Actual',
    observacionApiqueUltimaSolicitudApique: 'Observación Apique Ultima Solicitud Apique',
    rutasTransporte: 'Transporte',
    levantamientoTopografico: 'Levantamiento Topografico',
    modulacionLosas: 'Modulación Losas',
    fichaEvaluacionEstructural: 'Ficha Evaluación Estructural',
    informacionDeDisenio: 'Información de Diseño',
    consultaRedes: 'Consulta Redes',
    posibleDanioRedes: 'Posible daño en Redes',
    tieneRadicadoSalida: 'Tiene Radicado de Salida',
    tipoRadicadoRespuestaReserva: 'Tipo Radicado Respuesta Reserva',
    fechaAsignacionIngenieroDisenio: 'Fecha Asignación Ingeniero de Diseño',
    ingenieroDisenio: 'Ingeniero de Diseño',
    nombreResidenteSocial: 'Nombre Residente Social',
    jornadaProgramacionPeriodica: 'Jornada Programacion',
    fechaSolicitudSmvl: 'Fecha Solicitud SMVL',
    numeroRadicadoSmvl: 'Número Radicado SMVL',
    observacionesSmvl: 'Observación SMVL',
    listaChequeoSmvl: 'Lista Chequeo SMVL',
    listaChequeoGasa: 'Lista Chequeo GASA',
    fechaSolicitudGasa: 'Fecha Solicitud GASA',
    numeroRadicadoGasa: 'Número Radicado GASA',
    observacionesGasa: 'Observcaiones GASA',
    observacionesCierre: 'Observaciones Cierre intervención',
    estadoProgramacionVisita: 'Estado Programación Visita',
    fechaProgramacionDiaria: 'Fecha Programación Diaria',
    jornada: 'Jornada',
    fechaInforme: 'Fecha Informe',
    estadoObra: 'Estado Obra',
    estadoRegistroDiarioCuadrilla: 'estado registro Diario Cuadrilla',
    avancePorcentajeAcumuladoObra: 'Avance Porcentaje Acumulado Obra',
    kmCarrilLineal: 'Km Carril Lineal',
    kmCarrilObra: 'Km Carril Obra',
    vigencia: 'Vigencia',
    periodicidad: 'Periodicidad',
    periodo: 'Período',
    duracionPlaneada: 'Duración Planeada',
    estadoProgramacionPk: 'Estado Programación Pk',
    estadoProgramacion: 'Estado Programación',
    programa: 'Programa',
    estadoActividad: 'Estado Actividad',
    turnoResidenteSocial: 'Turno Ejecución Residente Social',
    tipoSeccionVial: 'Sección Vial',
    enSeguimiento: 'En Seguimiento',
    fechaSeguimiento: 'Fecha Segimiento',
    residenteSocial: 'Residente Social',
    tieneResidenteSocial: 'Residente Social Asignado',
    turnoResidenteAmbiental: 'Turno Ejecución Residente Ambiental',
    nombreResidenteAmbiental: 'Nombre Residente Ambiental',
    residenteAmbiental: 'Residente Ambiental',
    tieneResidenteAmbiental: 'Residente Ambiental Asignado',
    turnoResidenteSST: 'Turno Ejecución Residente SST',
    nombreResidenteSST: 'Nombre Residente SST',
    residenteSST: 'Residente SST',
    tieneResidenteSST: 'Residente SST Asignado',
    fechasIntervencion: 'fechas Intervencion',
    origenSin: 'origen',
    requiereActualizacionDiagnostico: 'Requiere Act. Diagnóstico',
    numeroActaIntervencion: 'Número Acta Intervención',
    tieneSolicitudLaboratorio: 'Tiene Solicitud Laboratorio',
    espesorDisenio: 'Espesor Diseño',
    tipoResultado: 'Tipo Resultado',
    formatoDDMMYYYY: 'DD-MM-YYYY',
    frecuencia: 'Frecuencia',
    tipoMezcla: 'Tipo Mezcla',
    fechaDespacho: 'Fecha Despacho',
    tipoMaterial: 'Tipo Material',
    cantidadMaterial: 'Cantidad Material (KG)',
    responsableObra: 'Responsable de obra',
    telResponsableObra: 'Tel respnsable de obra',
    ...PATHS,
    ...PERMISOS
};
