import { CONST_SHARED } from 'src/app/shared/constantes-shared';

/** 
*  Constantes con valores de URL´s relacionadas con el componente 
*/
export const PATHS = {
  // path_complemento: '',
};

/**
 * Hommologación de las constantes de permisos usados por el componente 
 * con los asignados en la base de datos
 */
export const PERMISOS = {
  // permiso_intervencion_complemento: '',
};

/**
 * Declaración de constantes de etiquetas propias usadas en el componente
 */
export const CONST_REGISTRO_PROGRAMACION_DIARIA_TRABAJO = {  
  registroProgramacionDiaria: "Registrar programación diaria",
  listarProgramacionDiaria: "Listar programación diaria",

  activo: 'Activo',
  actaVisitaTecnica: 'Acta de visita técnica',
  disenoApique: 'Diseño - Apique',
  revisarDiseno: 'revisar diseño (informacion de diseño)',
  apellidos: 'Apellidos',
  asignar: 'Asignar',
  seccionVial: 'Sección vial',
  solicitante: 'Solicitante',
  uso_via: 'Uso vía',
  tipo_malla: 'Tipo malla',
  transitabilidad: 'Transitabilidad',
  programa: 'Programa',
  formularioOrigenRevisarVisita: 'revisarDiagnostico',
  programar: 'Programar',
  tipo_superficie: 'Tipo superficie',
  tipo_intervencion_total: 'Tipo intervención total',
  eje_vial: 'Eje vial',
  desde: 'Desde',
  hasta: 'Hasta',
  actividad: 'Actividad',
  uplaNombre: 'UPZ',
  prioritarios: 'Prioritarios',
  estrategia: 'Estrategia de intervención',
  localidadNombre: 'Nombre de la localidad',
  barrioNombre: 'Nombre del barrio',
  aporte_cumplimiento: 'Aporte al cumplimiento de metas',
  coordinacion_interinstucional: 'Coordinación interinstitucional',
  tipo_intervencion: 'Tipo intervención',
  detalle_tipo_intervencion: 'Determinación del tipo de intervención',
  impacto_social: 'Impacto Social',
  tipo_factor: 'Tipo factor',
  campoRequerido: 'Campo requerido',
  campoNoValido: 'Campo no válido',
  cuadrante: 'Cuadrante',
  actividadAgrupada: 'Actividad agrupada',
  ancho: 'Ancho (m)',
  andOr: 'And / Or',
  area: 'Area (m2)',
  prioridad: 'Prioridad',
  autocomplete: 'autocomplete',
  barrio: 'Barrio',
  busquedaAvanzada: 'Busqueda avanzada',
  calendariosEquipo: 'Calendarios equipos',
  calendariosPersona: 'Calendarios personas',
  calificacionPci: 'Calificación Pci',
  capa: 'Capa',
  campo: 'Campo',
  civ: 'CIV',
  contiene: 'Contiene',
  consultaAvanzada: 'Consulta avanzada',
  date: 'date',
  dateRange: 'dateRange',
  diagnosticoId: 'Diagnóstico',
  diferente: 'Diferente',
  direccion: 'Dirección',
  directorObra: 'Director de obra',
  directorObraResidente: 'Director de obra y residente',
  enseguimiento: 'En seguimiento',
  estadoPk: 'Estado PK',
  estadosPk: {
    pendiente_programacion: 'PENDIENTE_PROGRAMACION_VISITA_TECNICA'
  },
  equipo: 'Equipo',
  equipos: 'Equipos',
  fecha: 'Fecha',
  fechaDesde: 'Fecha desde',
  fechaHasta: 'Fecha hasta',
  fechaFin: 'Fecha fin',
  fechaSolicitudProgramacion: 'Fecha solicitud programación',
  fechaVisita: 'Fecha visita',
  fechaDiagnostico: 'Fecha diagnóstico',
  fechaVisitaTecnica: 'Fecha visita técnica',
  fechaProgramacion: 'Fecha de programación',
  fechaInicioVisita: 'Fecha inicio de la visita',
  fechaFinVisita: 'Fecha fin de la visita',
  finaliza: 'Finaliza',
  fotos: 'Fotos',
  igual: 'Igual',
  inicia: 'Inicia',
  indicePriorizacion: 'Índice Priorización',
  list: 'list',
  listLocal: 'listLocal',
  localidad: 'Localidad',
  mantenimientos: 'Mantenimientos',
  mantenimiento:  'Mantenimiento',
  mayor: 'Mayor',
  mayorIgual: 'Mayor igual',
  menor: 'Menor',
  menorIgual: 'Menor igual',
  notQuery: 'No se ha ingresado una consulta para buscar',
  nombres: 'Nombres',
  origen: 'Origen',
  operador: 'Operador',
  persona: 'Persona',
  personas: 'Personas',
  pk: 'Pk',
  responsable: 'Responsable',
  asignacion: 'Asignación',
  segimiento: 'SEGIMIENTO',
  solicitudFecha: 'Solicitud Fecha',
  tipoSolicitud: 'Tipo solicitud',
  text: 'text',
  tieneRutasTransporte: 'Tiene Rutas Transporte',
  tipoIntervencionTotal: 'Tipo Intervención Total',
  tipoMalla: 'Tipo de malla vial',
  tipoSuperficie: 'Tipo Superficie',
  usoVia: 'Uso de la Vía',
  vacio: 'Vacio',
  valor: 'Valor',
  valorUnico: 'Valor único',
  vistaDiagnostico: 'Vista Diagnóstico',
  vistaVerificacion: 'Vista Verificación',
  query: 'Query',
  zona: 'Zona',
  aporteCumplimiento: 'Aporte Cumplimiento',
  coordinacionInterinst: 'Coordinacion Interinst',
  determTipoIntervencion: 'Determ Tipo Intervencion',
  diagnosticoEncabezado: 'Diagnostico Encabezado',
  impactoSocial: 'Impacto Social',
  observaciones: 'Observaciones',
  usuario: 'Usuario',
  unidadMuestreo: 'Unidad muestreo',
  abscisaInicial: 'Abscisa inicial',
  abscisaFinal: 'Abscisa Final',
  vehiculo: 'Vehículo',
  tipo_falla: 'Tipo falla',
  severidad: 'Severidad',
  longitud: 'Longitud',
  longitudLosa: 'Longitud losa',
  anchoLosa: 'Ancho losa',
  numeroLosas: 'Número de losas',
  numeroVisitasProgramadasSinRealizar: 'Número de visitas programadas sin realizar',
  numeroVisitasProgramadasVigentes: 'Número de visitas programadas vigentes',
  tipoIntervencion: 'Tipo de intervención',
  'radicadoEntrada': 'Radicado Entada',
  'radicadoSalida': 'Radicado Salida',
  fechaAsignacion: 'Fecha Asignación',
  'vencimiento': 'Vencimiento',
  verDetallePk: 'Ver detalle PK',
  verActividad: 'Ver actividad',
  'kmCarrilImpacto': 'KM Carril del PK',
  'radicadoSolicitudReserva': 'Radicado Solicitud Reserva',
  'radicadoRespuestaReserva': 'Radicado Respuesta de Reserva',
  tipoActividad: 'Tipo de actividad',
  mantenimientoSinDiagnostico: 'El mantenimiento no posee un diagnostico',
  archivo: 'Archivo',
  verificarProgramar: 'Verificar y programar visitas',
  verProgramacion: 'Ver programación',
  consultarProgramar: 'Consultar programación visitas',
  anchoPK: 'Ancho del PK',
  longitudPK: 'Longitud del PK',
  areaPK: 'Área del PK',
  mensajeAreaPK: 'el área de la falla no puede superar el área del Pk',
  mensajeAreaUnidad: 'el área de la falla no puede superar el área de la unidad',
  responsableDisenio: 'Responsable de diseño',
  residenteObra: 'Residente de Obra',
  fechaRegistroProgramacion: 'Fecha creación programación diaria',
  jornada: 'Jornada',
  fechaProgramacionDiaria: 'Fecha programacion diaria',
  warningPersonalRequerido: 'Debe existir un registro en la sección: Personal',
  confirmarSalidaSeccion: {
    mensaje: '¿Confirma que desea salir de la sección sin guardar cambios?',
    titulo: 'Confirmando acción'
  },
  ...CONST_SHARED,
  ...PATHS,
  ...PERMISOS,
};